### ISSUE TITLE
Incorrect behavior (no files bundled) on Windows with lowercase drive letter

### ISSUE THREAD

**Issue by lmartorella** [fuse-box/fuse-box#189]
Hello,
This project seems very promising, we falled in love in less of one day!

We found an issue on Windows machine, that can be replicated running fuse bundler (even the sample apps) in a prompt where _the drive is loaded with a lowercase letter_.
You should be able to create such prompt using a Windows shortcut to cmd.exe and setting the "Start in" field with an absolute path that starts with a lowercase letter (e.g. 'e:\dev').

Strangely, Windows allows this, and then any reference to absolute path in applications becomes lowercase, making some regex in PathMaster to fail (NODE_MODULE).

The issue is quite nasty because difficult to spot (FuseBox in that case will produce an empty bundle without any error).

Thank you for the support on this project!
 
![capture](https://cloud.githubusercontent.com/assets/747421/23018659/14c940ac-f43f-11e6-9ca6-e7559e82207f.png)
Luciano

**Comment by nchanged** [comment]
Welcome @lmartorella ! 
Thanks for the issue! 
@devmondo you got windows, can you reproduce that?

**Comment by devmondo** [comment]
@lmartorella welcome to the party and thanks for the kind words. :)

we are really rapidly fixing and streamlining all bugs, 

I tried to do like what you said and I got no issues, but maybe I am trying it wrong so I attached an image.
please let us know how we can hunt this
 
![image](https://cloud.githubusercontent.com/assets/1266367/23019358/5089520a-f45b-11e6-9121-2ef3ebe1b361.png)

**Comment by lmartorella** [comment]
Right, you have a capital C: in the 'Start in'.
Try to use a lower case c:\... path in 'Start in'. When you then reopen the link you will see "c:\projects\..." in your current path, and the issue should be replicated then.
Thanks!

**Comment by devmondo** [comment]
@lmartorella  i did what you suggested still works :)
![image](https://cloud.githubusercontent.com/assets/1266367/23019718/3135bb30-f45d-11e6-8c07-3f6a2598ea23.png)

**Comment by lmartorella** [comment]
You have actually replicated the bug! No files bundled :)

**Comment by devmondo** [comment]
hahaha
maybe this one in gitter is  also related 
https://files.gitter.im/fusebox-bundler/Lobby/ZVh8/blob

**Comment by lmartorella** [comment]
Mmm actually it seems a bug in PathMaster.js, where an absolute path is tested against the NODE_MODULE regex to check if it comes from node_modules.
That regex tests the first character for being in the range a-z@, that in case of Windowss-with-lowercase-drive-letter actually matches (and incorrectly creates a wrong path prepending the node_modules abs root)...

**Comment by nchanged** [comment]
@lmartorella wow, nice one!

**Comment by nchanged** [comment]
@lmartorella could you suggest a fix?

**Comment by lordgreg** [comment]
I'm not sure, however, I think I'm having the exact same issue here (In powershell AND git bash on Windows 10):
```
$ node fuse.js
21:54:42 : Launching dev server on port 4445
C:\Development\fusebox-ionic2\.fusebox\cache\1.3.115\C%3A%5CDevelopment%5Cfusebox-ionic2.%2Fwww%2Fbundle.js\fusebox-hot-reload%400.0.0 was not found
C:\Development\fusebox-ionic2\.fusebox\cache\1.3.115\C%3A%5CDevelopment%5Cfusebox-ionic2.%2Fwww%2Fbundle.js\fusebox-websocket%400.0.0 was not found
C:\Development\fusebox-ionic2\.fusebox\cache\1.3.115\C%3A%5CDevelopment%5Cfusebox-ionic2.%2Fwww%2Fbundle.js\events%400.0.0 was not found
C:\Development\fusebox-ionic2\.fusebox\cache\1.3.115\C%3A%5CDevelopment%5Cfusebox-ionic2.%2Fwww%2Fbundle.js\reflect-metadata%400.1.9 was not found
C:\Development\fusebox-ionic2\.fusebox\cache\1.3.115\C%3A%5CDevelopment%5Cfusebox-ionic2.%2Fwww%2Fbundle.js\%40angular%2Fplatform-browser-dynamic%402.2.1 was not found
C:\Development\fusebox-ionic2\.fusebox\cache\1.3.115\C%3A%5CDevelopment%5Cfusebox-ionic2.%2Fwww%2Fbundle.js\%40angular%2Fcompiler%402.2.1 was not found
C:\Development\fusebox-ionic2\.fusebox\cache\1.3.115\C%3A%5CDevelopment%5Cfusebox-ionic2.%2Fwww%2Fbundle.js\%40angular%2Fcore%402.2.1 was not found
C:\Development\fusebox-ionic2\.fusebox\cache\1.3.115\C%3A%5CDevelopment%5Cfusebox-ionic2.%2Fwww%2Fbundle.js\rxjs%405.0.0-beta.12 was not found
C:\Development\fusebox-ionic2\.fusebox\cache\1.3.115\C%3A%5CDevelopment%5Cfusebox-ionic2.%2Fwww%2Fbundle.js\%40angular%2Fplatform-browser%402.2.1 was not found
C:\Development\fusebox-ionic2\.fusebox\cache\1.3.115\C%3A%5CDevelopment%5Cfusebox-ionic2.%2Fwww%2Fbundle.js\%40angular%2Fcommon%402.2.1 was not found
C:\Development\fusebox-ionic2\.fusebox\cache\1.3.115\C%3A%5CDevelopment%5Cfusebox-ionic2.%2Fwww%2Fbundle.js\ionic-angular%402.0.1 was not found
C:\Development\fusebox-ionic2\.fusebox\cache\1.3.115\C%3A%5CDevelopment%5Cfusebox-ionic2.%2Fwww%2Fbundle.js\%40angular%2Fforms%402.2.1 was not found
C:\Development\fusebox-ionic2\.fusebox\cache\1.3.115\C%3A%5CDevelopment%5Cfusebox-ionic2.%2Fwww%2Fbundle.js\%40angular%2Fhttp%402.2.1 was not found
C:\Development\fusebox-ionic2\.fusebox\cache\1.3.115\C%3A%5CDevelopment%5Cfusebox-ionic2.%2Fwww%2Fbundle.js\ionic-native%402.4.1 was not found
```

Exactly, the files aren't there. Same repo, cloned on Linux (elementary os), no issues.

**Comment by nchanged** [comment]
That's cache. Please nuke it =)
Cache is not perfect.. we know.. we know..

**Comment by lordgreg** [comment]
Ty for your answer @nchanged. Even if I rimraf the .fusebox folder, I get the same error.

**Comment by nchanged** [comment]
Did not mean to be disrespectful, I am responding to 20 people at the same time. 
You log looked like a "normal" bug. I think @devmondo is on to something there.

**Comment by devmondo** [comment]
@lmartorella @lordgreg it is fixed will be merged tomorrow :)

**Comment by lmartorella** [comment]
Thanks!
I was going to suggest the same fix. 
I don't know in which other contexts this regex should react. On a *nix environment an absolute path always starts with '/', so the regex has worked with no issues on Windows too since the disk letter is often capital (are node modules names always starting with a lowercase letter?).
In case we wants to isolate absolute paths here, perhaps a more robust solution here is to use the path 'isAbsolute' function, that should support all possible scenarios.

By the way, thanks for the fix.

**Comment by lordgreg** [comment]
Hi.

Just tried latest version and having the same issues:
```
$ node fuse.js
17:42:11 : Launching dev server on port 4445
C:\Development\fusebox-ionic2\.fusebox\cache\1.3.117\C%3A%5CDevelopment%5Cfusebox-ionic2.%2Fwww%2Fbundle.js\fusebox-hot-reload%400.0.0 was not found
C:\Development\fusebox-ionic2\.fusebox\cache\1.3.117\C%3A%5CDevelopment%5Cfusebox-ionic2.%2Fwww%2Fbundle.js\fusebox-websocket%400.0.0 was not found
C:\Development\fusebox-ionic2\.fusebox\cache\1.3.117\C%3A%5CDevelopment%5Cfusebox-ionic2.%2Fwww%2Fbundle.js\events%400.0.0 was not found
C:\Development\fusebox-ionic2\.fusebox\cache\1.3.117\C%3A%5CDevelopment%5Cfusebox-ionic2.%2Fwww%2Fbundle.js\reflect-metadata%400.1.9 was not found
C:\Development\fusebox-ionic2\.fusebox\cache\1.3.117\C%3A%5CDevelopment%5Cfusebox-ionic2.%2Fwww%2Fbundle.js\zone.js%400.6.26 was not found
C:\Development\fusebox-ionic2\.fusebox\cache\1.3.117\C%3A%5CDevelopment%5Cfusebox-ionic2.%2Fwww%2Fbundle.js\%40angular%2Fplatform-browser-dynamic%402.2.1 was not found
C:\Development\fusebox-ionic2\.fusebox\cache\1.3.117\C%3A%5CDevelopment%5Cfusebox-ionic2.%2Fwww%2Fbundle.js\%40angular%2Fcompiler%402.2.1 was not found
C:\Development\fusebox-ionic2\.fusebox\cache\1.3.117\C%3A%5CDevelopment%5Cfusebox-ionic2.%2Fwww%2Fbundle.js\%40angular%2Fcore%402.2.1 was not found
C:\Development\fusebox-ionic2\.fusebox\cache\1.3.117\C%3A%5CDevelopment%5Cfusebox-ionic2.%2Fwww%2Fbundle.js\rxjs%405.0.0-beta.12 was not found
C:\Development\fusebox-ionic2\.fusebox\cache\1.3.117\C%3A%5CDevelopment%5Cfusebox-ionic2.%2Fwww%2Fbundle.js\%40angular%2Fplatform-browser%402.2.1 was not found
C:\Development\fusebox-ionic2\.fusebox\cache\1.3.117\C%3A%5CDevelopment%5Cfusebox-ionic2.%2Fwww%2Fbundle.js\%40angular%2Fcommon%402.2.1 was not found
C:\Development\fusebox-ionic2\.fusebox\cache\1.3.117\C%3A%5CDevelopment%5Cfusebox-ionic2.%2Fwww%2Fbundle.js\ionic-angular%402.0.1 was not found
C:\Development\fusebox-ionic2\.fusebox\cache\1.3.117\C%3A%5CDevelopment%5Cfusebox-ionic2.%2Fwww%2Fbundle.js\%40angular%2Fforms%402.2.1 was not found
C:\Development\fusebox-ionic2\.fusebox\cache\1.3.117\C%3A%5CDevelopment%5Cfusebox-ionic2.%2Fwww%2Fbundle.js\%40angular%2Fhttp%402.2.1 was not found
C:\Development\fusebox-ionic2\.fusebox\cache\1.3.117\C%3A%5CDevelopment%5Cfusebox-ionic2.%2Fwww%2Fbundle.js\ionic-native%402.4.1 was not found
```

package.json:
```
{
  "name": "fusebox-angular",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "node ./fuse.js",
    "test": "set TS_NODE_PROJECT=./src/tsconfig.mocha.json&& mocha  --opts ./test/mocha.opts -G",
    "coverage": "set TS_NODE_PROJECT=./src/tsconfig.mocha.json&& nyc mocha  --opts ./test/mocha.coverage.opts -G"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/fuse-box/angular2-example.git"
  },
  "author": "",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/fuse-box/angular2-example/issues"
  },
  "homepage": "https://github.com/fuse-box/angular2-example#readme",
  "devDependencies": {
    "@types/chai": "^3.4.34",
    "@types/core-js": "^0.9.35",
    "@types/lodash": "^4.14.44",
    "@types/mocha": "^2.2.38",
    "@types/node": "^6.0.52",
    "@types/sinon": "^1.16.34",
    "chai": "^3.5.0",
    "fuse-box": "^1.3.117",
    "jsdom-no-contextify": "^3.1.0",
    "mocha": "^3.2.0",
    "node-sass": "^4.1.1",
    "nyc": "^10.1.2",
    "sinon": "^1.17.7",
    "ts-node": "^2.0.0",
    "typescript": "^2.1.4"
  },
  "dependencies": {
    "@angular/common": "^2.3.1",
    "@angular/compiler": "^2.3.1",
    "@angular/core": "^2.3.1",
    "@angular/forms": "^2.3.1",
    "@angular/http": "^2.3.1",
    "@angular/material": "^2.0.0-beta.0",
    "@angular/platform-browser": "^2.3.1",
    "@angular/platform-browser-dynamic": "^2.3.1",
    "@angular/router": "^3.3.1",
    "angular-in-memory-web-api": "^0.2.1",
    "core-js": "^2.4.1",
    "lodash": "^4.17.3",
    "rxjs": "^5.0.1",
    "zone.js": "^0.7.2"
  },
  "nyc": {
    "include": [
      "src/**/*.ts"
    ],
    "exclude": [
      "src/**/*.spec.ts",
      "src/**/*.module.ts",
      "node_modules/",
      "src/**/main.ts"
    ],
    "extension": [
      ".ts"
    ],
    "require": [
      "ts-node/register"
    ],
    "reporter": [
      "html",
      "text-summary",
      "text",
      "lcov"
    ],
    "all": true,
    "sourceMap": true,
    "instrument": true
  }
}
```

fuse.js
```
const fsbx = require('fuse-box');

const fuseBox = fsbx.FuseBox.init({
  homeDir: "./src",
  outFile: "./www/bundle.js",

  plugins: [
    [
      fsbx.SassPlugin({ outputStyle: 'compressed' }),
      fsbx.CSSPlugin()
    ],
    fsbx.TypeScriptHelpers(),
    fsbx.JSONPlugin(),
    fsbx.HTMLPlugin({ useDefault: false })
  ]

});

fuseBox.devServer('>app/main.ts', {
  port: 4445
});
```

Browser console log shows:
![image](https://cloud.githubusercontent.com/assets/480546/23074296/adbaf446-f538-11e6-843d-7a211e91b0a7.png)

main.ts is:
```
import 'reflect-metadata';
// Angular wants it
import 'zone.js/dist/zone';

import "./app.scss";
import "../theme/variables.scss";

import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';

import { AppModule } from './app.module';

platformBrowserDynamic().bootstrapModule(AppModule);
```

**Comment by nchanged** [comment]
And you are 100% sure it's not cache related issue?! 
Yeah, that fix did not go through the tests. Still working on it.

**Comment by lordgreg** [comment]
I don't know. I've deleted the whole `.fusebox` directory and still facing the same issue. 

However,.. I'm not quite sure if this isn't somehow related to ionic2.  Here's the default simple ionic2 app which should work with slight metadata and zone modifications in main.ts: https://github.com/driftyco/ionic-conference-app

Thank you for replying.

**Comment by indrimuska** [comment]
Guys this issue is not fixed, nothing has been changed in the source code!

As @lmartorella [said](https://github.com/fuse-box/fuse-box/pull/195#issuecomment-281284046), the right fix is to use negative lookahead: `/^([a-z@](?!:).*)$/`

Here it is some basic tests:
 - `C:\users\foo` -> no match
 - `c:\users\foo` -> no match
 - `/users/foo` -> no match
 - `@types/foo` -> 1 match
 - `types/foo` -> 1 match
 - `types/foo/bar` -> 1 match

Could you please fix or at least tell us to open a PR?
Thanks :)

**Comment by nchanged** [comment]
@indrimuska feel free to open a PR ;-) if you have an idea how to fix it!
Thank you ;-)

**Comment by lmartorella** [comment]
Fixed in 1.3.122. Thx!
